import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/image';
import design from '../public/design.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	return (
		<>
			<div className={darkMode ? 'dark' : ''}>
				<Head>
					<title>Wilmer Martinez Portfolio</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
					{/* add min-h-screen to section to take full vh */}
					<section className="">
						<nav className="py-10 mb-12 flex justify-between">
							<h1 className="text-xl font-burtons dark:text-white">WM</h1>
							<ul className="flex items-center">
								<li>
									<BsFillMoonStarsFill
										onClick={() => setDarkMode(!darkMode)}
										className="cursor-pointer text-2xl dark:fill-white"
									/>
								</li>
								<li>
									<a
										className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
										href="#"
									>
										Resume
									</a>
								</li>
							</ul>
						</nav>
						<div className="text-center p-10">
							<h2 className="text-5xl py-2 text-teal-600 font-medium font-burtons md:text-6xl">
								Wilmer Martinez
							</h2>
							<h3 className="text-2xl py-2 md:text-3xl dark:text-white">
								Full Stack Web Developer
							</h3>
							<p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
								As a lifelong tech enthusiast, I have always been drawn to the
								world of web development. With a backgorund in computer science
								and a natural aptitude for problem-solving, I have the skills
								and knowledge to create functional and visually appealing
								websites. In my spare time, you can find me tinkering with new
								technologies, staying up-to-date with the latest web development
								trends, and collaborating with other professionals in the
								industry.
							</p>
						</div>
						<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
							<AiFillLinkedin />
							<AiFillGithub />
						</div>
					</section>
					<section>
						<div>
							<h3 className="text-3xl py-1 dark:text-white">Skills</h3>
							<p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
								"Web development skills are like spices - a little goes a long
								way, but the right blend can take your site from bland to
								grand."
							</p>
						</div>
						<div className="lg:flex gap-10">
							<div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
								<Image
									className="mx-auto"
									src={design}
									width={100}
									height={100}
								/>
								<h3 className="text-lg font-medium pt-8 pb-2">Front End</h3>
								<p className="py-2">
									Front-end tools used to develop the user interface and user
									experience of a website or application.
								</p>
								<h4 className="py-4 text-teal-600">Front End tools I use :</h4>
								<ul className="text-gray-800 py-2 dark:bg-gray-200 rounded-lg font-bold">
									<li>JavaScript</li>
									<li>React</li>
									<li>NextJS</li>
									<li>HTML5</li>
									<li>CSS3</li>
									<li>BootStrap</li>
									<li>TailwindCSS</li>
								</ul>
							</div>
							<div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
								<Image
									className="mx-auto"
									src={design}
									width={100}
									height={100}
								/>
								<h3 className="text-lg font-medium pt-8 pb-2">Back End</h3>
								<p className="py-2">
									Back-end tools used to build and manage the server-side
									infrastructure and logic of a website or application.
								</p>
								<h4 className="py-4 text-teal-600">Back End tools I use</h4>
								<ul className="text-gray-800 py-2 dark:bg-gray-200 rounded-lg font-bold">
									<li>Node</li>
									<li>Express</li>
									<li>MongoDB</li>
									<li>MySQL</li>
									<li>Sequelize</li>
									<li>GraphQL</li>
									<li>REST API</li>
								</ul>
							</div>
							<div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
								<Image
									className="mx-auto"
									src={design}
									width={100}
									height={100}
								/>
								<h3 className="text-lg font-medium pt-8 pb-2">Tools</h3>
								<p className="py-2">
									Development tools that are used to support the development,
									testing, and maintenance of software applications.
								</p>
								<h4 className="py-4 text-teal-600">Dev Tools I use</h4>
								<ul className="text-gray-800 py-2 dark:bg-gray-200 rounded-lg font-bold">
									<li>GitHub</li>
									<li>Git</li>
									<li>Agile</li>
									<li>Heroku</li>
									<li>PWA</li>
									<li>TDD</li>
									<li>Webpack</li>
								</ul>
							</div>
						</div>
					</section>
					<section>
						<div>
							<h3 className="text-3xl py-1 dark:text-white">Projects</h3>
							<p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
								some projects
							</p>
						</div>
						<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
							<div className="basis-1/3 flex-1">
								<Image
									src={web1}
									className="rounded-lg object-cover"
									width={'100%'}
									height={'100%'}
									layout="responsive"
								/>
							</div>
							<div className="basis-1/3 flex-1">
								<Image
									src={web2}
									className="rounded-lg object-cover"
									width={'100%'}
									height={'100%'}
									layout="responsive"
								/>
							</div>
							<div className="basis-1/3 flex-1">
								<Image
									src={web3}
									className="rounded-lg object-cover"
									width={'100%'}
									height={'100%'}
									layout="responsive"
								/>
							</div>
							<div className="basis-1/3 flex-1">
								<Image
									src={web4}
									className="rounded-lg object-cover"
									width={'100%'}
									height={'100%'}
									layout="responsive"
								/>
							</div>
							<div className="basis-1/3 flex-1">
								<Image
									src={web5}
									className="rounded-lg object-cover"
									width={'100%'}
									height={'100%'}
									layout="responsive"
								/>
							</div>
							<div className="basis-1/3 flex-1">
								<Image
									src={web6}
									className="rounded-lg object-cover"
									width={'100%'}
									height={'100%'}
									layout="responsive"
								/>
							</div>
						</div>
					</section>
				</main>
				<footer className="py-8 text-center text-gray-600 dark:text-gray-400 bg-gray-200 dark:bg-gray-800">
					<p>Copyright &copy; {new Date().getFullYear()} Wilmer Martinez</p>
					<div className="flex justify-center mt-4">
						<a href="#">
							<AiFillLinkedin className="text-xl mx-4" />
						</a>
						<a href="#">
							<AiFillGithub className="text-xl mx-4" />
						</a>
					</div>
				</footer>
			</div>
		</>
	);
}
