import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/image';
import frontend from '../public/frontend.png';
import server from '../public/server.png';
import tools from '../public/tools.png';
import musicmarket from '../public/musicmarket.png';
import deepthoughts from '../public/deepthoughts.png';
import photoport from '../public/photoport.png';
import musicenvivo from '../public/musicenvivo.png';
import { useState } from 'react';
import React, { useRef } from 'react';
import emailjs from '@emailjs/browser';
//import EmailSentModal from '../components/EmailModal';

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	const form = useRef();
	const sendEmail = (e) => {
		e.preventDefault();

		emailjs
			.sendForm(
				'service_cyxh6g9',
				'template_0i6x6lr',
				form.current,
				'avDf71P-wy8sNIBQc'
			)
			.then(
				(result) => {
					console.log(result.text);
				},
				(error) => {
					console.log(error.text);
				}
			);
		e.target.reset();
	};
	return (
		<>
			<div className={darkMode ? 'dark' : ''}>
				<Head>
					<title>Wilmer Martinez Portfolio</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
					{/* add min-h-screen to section to take full vh */}
					<section className="">
						<nav className="py-10 mb-12 flex justify-between">
							<h1 className="text-xl font-burtons dark:text-white">WM</h1>
							<ul className="flex items-center">
								<li>
									<BsFillMoonStarsFill
										onClick={() => setDarkMode(!darkMode)}
										className="cursor-pointer text-2xl dark:fill-white"
									/>
								</li>
								<li>
									<a
										className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
										href="https://drive.google.com/file/d/1TK6vL4SM8r7kdgdF4ktqcmivsV66I7PM/view?usp=sharing"
										target="_blank"
										rel="noopener noreferrer"
									>
										Resume
									</a>
								</li>
							</ul>
						</nav>
						<div className="text-center p-10">
							<h2 className="text-5xl py-2 text-teal-600 font-medium font-burtons md:text-6xl">
								Wilmer Martinez
							</h2>
							<h3 className="text-2xl py-2 md:text-3xl dark:text-white">
								Full Stack Web Developer
							</h3>
							<p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
								As a lifelong tech enthusiast, I have always been drawn to the
								world of web development. In 2022 I began training in modern app
								development at UC Davis Coding Bootcamp. With a backgorund in
								computer science and a natural aptitude for problem-solving, I
								have the skills and knowledge to create functional and visually
								appealing websites. In my spare time, you can find me tinkering
								with new technologies, staying up-to-date with the latest web
								development trends, and collaborating with other professionals
								in the industry.
							</p>
						</div>
						<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
							<a
								href="https://www.linkedin.com/in/wilmer-martinez/"
								target="_blank"
								rel="noopener noreferrer"
							>
								<AiFillLinkedin />
							</a>
							<a
								href="https://github.com/wilmr"
								target="_blank"
								rel="noopener noreferrer"
							>
								{' '}
								<AiFillGithub />
							</a>
						</div>
					</section>
					<section>
						<div>
							<h3 className="text-3xl py-1 dark:text-white">Skills</h3>
							<p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
								"Web development skills are like spices - a little goes a long
								way, but the right blend can take your site from bland to
								grand."
							</p>
						</div>
						<div className="lg:flex gap-10">
							<div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
								<Image
									className="mx-auto"
									src={frontend}
									width={100}
									height={100}
								/>
								<h3 className="text-lg font-medium pt-8 pb-2">Front End</h3>
								<p className="py-2">
									Front-end tools used to develop the user interface and user
									experience of a website or application.
								</p>
								<h4 className="py-4 text-teal-600">Front End tools I use :</h4>
								<ul className="text-gray-800 py-2 dark:bg-gray-200 rounded-lg font-bold">
									<li>JavaScript</li>
									<li>React</li>
									<li>NextJS</li>
									<li>HTML5</li>
									<li>CSS3</li>
									<li>BootStrap</li>
									<li>TailwindCSS</li>
								</ul>
							</div>
							<div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
								<Image
									className="mx-auto"
									src={server}
									width={100}
									height={100}
								/>
								<h3 className="text-lg font-medium pt-8 pb-2">Back End</h3>
								<p className="py-2">
									Back-end tools used to build and manage the server-side
									infrastructure and logic of a website or application.
								</p>
								<h4 className="py-4 text-teal-600">Back End tools I use</h4>
								<ul className="text-gray-800 py-2 dark:bg-gray-200 rounded-lg font-bold">
									<li>Node</li>
									<li>Express</li>
									<li>MongoDB</li>
									<li>MySQL</li>
									<li>Sequelize</li>
									<li>GraphQL</li>
									<li>REST API</li>
								</ul>
							</div>
							<div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
								<Image
									className="mx-auto"
									src={tools}
									width={100}
									height={100}
								/>
								<h3 className="text-lg font-medium pt-8 pb-2">Tools</h3>
								<p className="py-2">
									SWE tools used to support the development, testing, and
									maintenance of software applications.
								</p>
								<h4 className="py-4 text-teal-600">Dev Tools I use</h4>
								<ul className="text-gray-800 py-2 dark:bg-gray-200 rounded-lg font-bold">
									<li>GitHub</li>
									<li>Git</li>
									<li>Agile</li>
									<li>Heroku</li>
									<li>PWA</li>
									<li>TDD</li>
									<li>Webpack</li>
								</ul>
							</div>
						</div>
					</section>
					<section>
						<div>
							<h3 className="text-3xl py-1 dark:text-white">Projects</h3>
						</div>
						<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
							<div className="basis-1/3 flex-1">
								<h3 className="text-medium text-center">Music Market</h3>
								<a
									href="https://g02-music-market.herokuapp.com/"
									target="_blank"
									rel="noopener noreferrer"
								>
									<Image
										src={musicmarket}
										className="rounded-lg object-cover"
										width={'100%'}
										height={'100%'}
										layout="responsive"
									/>
								</a>
							</div>
							<div className="basis-1/3 flex-1">
								<h3 className="text-medium text-center">Deep Thoughts</h3>
								<a
									href="https://cryptic-wave-02667.herokuapp.com/"
									target="_blank"
									rel="noopener noreferrer"
								>
									<Image
										src={deepthoughts}
										className="rounded-lg object-cover"
										width={'100%'}
										height={'100%'}
										layout="responsive"
									/>
								</a>
							</div>
							<div className="basis-1/3 flex-1">
								<h3 className="text-medium text-center">Photo Port</h3>
								<a
									href="https://wilmr.github.io/photo-port/"
									target="_blank"
									rel="noopener noreferrer"
								>
									<Image
										src={photoport}
										className="rounded-lg object-cover"
										width={'100%'}
										height={'100%'}
										layout="responsive"
									/>
								</a>
							</div>
							<div className="basis-1/3 flex-1">
								<h3 className="text-medium text-center">Music en Vivo</h3>

								<a
									href="https://wilmr.github.io/Music-en-Vivo/"
									target="_blank"
									rel="noopener noreferrer"
								>
									<Image
										src={musicenvivo}
										className="rounded-lg object-cover"
										width={'100%'}
										height={'100%'}
										layout="responsive"
									/>
								</a>
							</div>
						</div>
					</section>
					<section className="mt-20 p-10 bg-gray-100 rounded-md">
						<h3 className="text-2xl font-medium mb-8 text-center">Contact</h3>
						<form ref={form} onSubmit={sendEmail}>
							<div className="flex flex-col md:flex-row md:items-center mb-6">
								<label htmlFor="name" className="w-full md:w-1/4 mb-2 md:mb-0">
									Name
								</label>
								<input
									type="text"
									id="name"
									name="user_name"
									placeholder="John Doe"
									className="w-full md:w-3/4 p-2 border rounded-md"
								/>
							</div>
							<div className="flex flex-col md:flex-row md:items-center mb-6">
								<label htmlFor="email" className="w-full md:w-1/4 mb-2 md:mb-0">
									Email
								</label>
								<input
									type="email"
									id="email"
									name="user_email"
									placeholder="john@example.com"
									className="w-full md:w-3/4 p-2 border rounded-md"
								/>
							</div>
							<div className="flex flex-col md:flex-row md:items-center mb-6">
								<label
									htmlFor="message"
									className="w-full md:w-1/4 mb-2 md:mb-0"
								>
									Message
								</label>
								<textarea
									id="message"
									name="message"
									placeholder="Enter your message here"
									rows="6"
									className="w-full md:w-3/4 p-2 border rounded-md"
								></textarea>
							</div>
							<div className="text-center">
								<button
									type="submit"
									value="Send"
									className="bg-teal-500 text-white px-4 py-2 rounded-md"
								>
									Submit
								</button>
							</div>
						</form>
					</section>
					<div className="py-10"></div>
				</main>
				<footer className="py-8 text-center text-gray-600 dark:text-gray-400 bg-gray-200 dark:bg-gray-800">
					<p>Copyright &copy; {new Date().getFullYear()} Wilmer Martinez</p>
					<div className="flex justify-center mt-4">
						<a
							href="https://www.linkedin.com/in/wilmer-martinez/"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillLinkedin className="text-xl mx-4" />
						</a>
						<a
							href="https://github.com/wilmr"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillGithub className="text-xl mx-4" />
						</a>
					</div>
				</footer>
			</div>
		</>
	);
}
